name: todo_app
description: "To Do Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  date_picker_timeline: ^1.2.6
  flutter_slidable: ^3.1.0
  firebase_core: ^2.29.0
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
